src/apps/carts/urls.py
from django.urls import path

from .controller import crud, views
from .controller import api

app_name  = 'cart'

urlpatterns = [
    path('', views.cart, name='index'),
    path('add_cart/<int:product_id>', crud.create_cart, name='add_cart'),
    path('add_cart', crud.create_cart, name='add_cart'),
    path('update_cart', crud.update_cart, name='update_cart'),
    path('remove_cart', crud.delete_cart, name='remove_cart'),
    path('get_cart_total', api.get_cart_total, name='get_cart_total'),
]

src/apps/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('contact/', views.contact, name='contact'),
]

src/apps/shop/urls.py
from django.urls import path
from .controller import views, api

urlpatterns = [
    path('', views.shop, name='shop'),
    path('category_list', views.category_list, name='category_list'),
    path('brand_list', views.brand_list, name='brand_list'),
    path('product/<int:product_id>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    # path('product_old/<int:product_id>/<slug:product_slug>/', views.product_detail_old, name='product_detail'), #TODO: remove it
    path('category_list/<int:category_id>/<slug:category_slug>/', views.products_by_category, name='products_by_category'),
    path('brand_list/<int:brand_id>/', views.products_by_brand, name='products_by_brand'),
    path('search/', views.search, name='search'),
    path('search_auto/', api.search_auto, name='search_auto'),
    path('ajaxcolour/', api.ajaxcolour, name='ajaxcolour'),
    path('submit_review/<int:product_id>/', api.submit_review, name='submit_review'),
]

src/mybrandedclothing/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('shop/', include('shop.urls')),
    path('cart/', include('carts.urls')),
    path('order/', include('order.urls')),
    path('voucher/', include('voucher.urls')),
    path('about/', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('test/', include('testapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.conf import settings
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _

# Create your models here.

class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must have an email address')

        if not username:
            raise ValueError('User must have an username')

        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


def get_profile_picture_path(instance=None, file=None, default=False):
    if default:
        return f'avatars\\default.png'
    extension = file.split(".")[-1]
    return f'avatars\\{instance.id}.{extension}'


class Account(AbstractBaseUser):
    first_name      = models.CharField(max_length=50)
    last_name       = models.CharField(max_length=50)
    username        = models.CharField(max_length=50, unique=True)
    email           = models.EmailField(max_length=100, unique=True)
    phone_number    = models.CharField(max_length=50)

    # optional info
    profile_picture = models.ImageField(upload_to=get_profile_picture_path, default=get_profile_picture_path(default=True))
    address_line_1 = models.CharField(max_length=500, blank=True)
    address_line_2 = models.CharField(max_length=500, blank=True)
    city = models.CharField(max_length=500, blank=True, null=True)
    county = models.CharField(max_length=500, blank=True, null=True)
    country = models.CharField(max_length=500, blank=True, null=True)

    # required
    date_joined     = models.DateTimeField(auto_now_add=True)
    last_login      = models.DateTimeField(auto_now_add=True)
    is_admin        = models.BooleanField(default=False)
    is_staff        = models.BooleanField(default=False)
    is_active        = models.BooleanField(default=True)
    is_superadmin        = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = MyAccountManager()

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True


def get_upload_path(instance, file):
    extension = file.split(".")[-1]
    return f'logo-upload\\{instance.user.id}\\{file}'

class Logo(models.Model):
    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to=get_upload_path)
    
    is_setup = models.BooleanField(default=False) # use order.ordered instead
    @property
    def is_exists(self):
        if self.image == '':
            return False
        return self.image.storage.exists(self.image.name)

src/apps/carts/models/additional_name.py
from django.db import models
from shop.models import Position

class AdditionalNameManager(models.Manager):
    def create(
            self,
            value: str,
            positions: list,
            *args, **kwargs):

        model_item: AdditionalName = super(AdditionalNameManager, self).create(value=value)
        model_item.save()
        for position_id in positions:
            model_item.positions.add(Position.objects.get(id=position_id))
        model_item.save()
        return model_item

class AdditionalName(models.Model):
    value = models.CharField(max_length=100, null=True, blank=True)
    positions = models.ManyToManyField(Position)

    objects = AdditionalNameManager()

src/apps/carts/models/logotext.py
from typing import Union
from accounts.models import Logo
from django.db import models
from django.core.files import File
from shop.models import Position

class LogoTextManager(models.Manager):
    def create(
            self,
            user_id: str,
            logo: Union[str, File],
            text: dict,
            positions: list,
            additional_positions: list = None,
            *args, **kwargs):
        model_item: Union[MainLogoText, AdditionalLogoText] = None

        if logo:
            type = BaseLogoText.TYPE_LOGO
            if isinstance(logo, str) and logo != '-1':
                logo_id = logo
            elif isinstance(logo, File):
                new_logo = Logo.objects.create(user_id=user_id, image=logo)
                logo_id = new_logo.id
            model_item = super(LogoTextManager, self).create(type=type, logo_id=logo_id)
            
        elif text:
            type = BaseLogoText.TYPE_TEXT
            value, font, color = [text.get(key, None)
                                  for key in ['value', 'font', 'color']]
            model_item = super(LogoTextManager, self).create(type=type, text=value, font=font, color=color)

        if model_item:
            model_item.save()

            for position_id in positions:
                model_item.positions.add(Position.objects.get(id=position_id))
            if additional_positions:
                for position_id in additional_positions:
                    model_item.additional_positions.add(Position.objects.get(id=position_id))
            return model_item


class BaseLogoText(models.Model):
    class Meta:
        abstract = True

    TYPE_LOGO = 'Logo'
    TYPE_TEXT = 'Text'
    TYPE = (
        ('Logo', 'Logo'),
        ('Text', 'Text'),
    )
    type = models.CharField(choices=TYPE, max_length=4)
    logo = models.ForeignKey(Logo, on_delete=models.SET_NULL, null=True) # TODO: set default logo
    text = models.CharField(max_length=100, null=True)
    font = models.CharField(max_length=100, null=True, blank=True)
    color = models.CharField(max_length=7, default='#000000')
    positions = models.ManyToManyField(Position)


class MainLogoText(BaseLogoText):
    # position = models.ForeignKey(Position, on_delete=models.SET_NULL, null=True)
    additional_positions = models.ManyToManyField(
        Position, related_name='logo_text_additional_positions')
    objects = LogoTextManager()

class AdditionalLogoText(BaseLogoText):
    objects = LogoTextManager()
    # positions = models.ManyToManyField(Position, related_name='additional_logo_text_positions')

src/apps/home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.http import request
from django.utils.html import mark_safe


class Setting(models.Model):
    title = models.CharField(max_length=150, blank=True)
    keywords = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    company = models.CharField(max_length=50, blank=True)
    address = models.CharField(max_length=100, blank=True)
    phone = models.CharField(max_length=15, blank=True)
    fax = models.CharField(max_length=15, blank=True)
    email = models.CharField(max_length=50, blank=True)
    about_us = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.BooleanField(default=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ContactMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True,max_length=20)
    email = models.CharField(blank=True,max_length=50)
    subject = models.CharField(blank=True,max_length=50)
    message = models.TextField(blank=True,max_length=255)
    status = models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

src/apps/testapp/models.py
from django.db import models

# Create your models here.

src/apps/accounts/forms.py
from django import forms
from .models import Account


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'form-control',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'
    }))

    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'password']


    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match!"
            )

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter last Name'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter Phone Number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email Address'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number', 'profile_picture', 
        'address_line_1', 'address_line_2', 'city', 'county', 'country']

        labels = {
            "first_name": "First name",
            "last_name": "Last name",
            "phone_number": "Phone number",
            "profile_picture": "Profile picture",
            "address_line_1": "Address line 1",
            "address_line_2": "Address line 2",
            "city": "City",
            "county": "County",
            "country": "Country",
        }

    def __init__(self, *args, **kwargs):
        initial = kwargs.pop('initial', {})
        user = kwargs.pop('user')

        for key in self.Meta.fields:
            if key in ['profile_picture']: continue
            if hasattr(user, key):
                initial[key] = initial.get(key) or getattr(user, key)
        kwargs['initial'] = initial

        super(EditProfileForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def clean(self):
        pass


class ChangePasswordForm(forms.ModelForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter old password',
        'class': 'form-control',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter new password',
        'class': 'form-control',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter confirm password',
        'class': 'form-control',
    }))

    field_order = ['old_password', 'password', 'confirm_password']

    class Meta:
        model = Account
        fields = ['password']

    def __init__(self, *args, **kwargs):
        super(ChangePasswordForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].label = "Your old password"
        self.fields['password'].label = "Enter new password"
        self.fields['confirm_password'].label = "Confirm your password"


    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()
        user: Account = self.instance

        old_password = cleaned_data.get('old_password')
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if not user.check_password(old_password):
            self._errors['old_password'] = self.error_class([
                "Wrong password!"])

        if len(password) < 6:
            self._errors['password'] = self.error_class([
                "Minimum 6 characters required!"])

        if password != confirm_password:
            self._errors['confirm_password'] = self.error_class([
                "Password does not match!"])

        return self.cleaned_data

src/apps/carts/forms.py
from .models import *
from django.forms import ModelForm, TextInput, Textarea


# class CartItemForm(ModelForm):
#     class Meta:
#         model = CartItem
#         fields = ['quantity']

src/apps/home/forms.py
from django import forms
from .models import ContactMessage
from django.forms import ModelForm, TextInput, Textarea


class ContactForm(ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name' : TextInput(attrs={'class': 'input', 'placeholder':'Your Name'}),
            'subject' : TextInput(attrs={'class': 'input', 'placeholder':'Subject'}),
            'email' : TextInput(attrs={'class': 'input', 'placeholder':'Your Email'}),
            'message' : Textarea(attrs={'class': 'input', 'placeholder':'Your Message', 'rows':'5'}),
        }

src/apps/order/forms.py
from django import forms


class OrderForm(forms.Form):
    first_name = forms.CharField(required=True, error_messages={'required': 'First name is required!'})
    last_name = forms.CharField(required=True, error_messages={'required': 'Last name is required!'})
    phone = forms.CharField(required=True, error_messages={'required': 'Phone number is required!'})
    email = forms.CharField(required=True, error_messages={'required': 'Email is required!'})
    country = forms.CharField(required=True, error_messages={'required': 'Country is required!'})
    address_line_1 = forms.CharField(required=True, error_messages={'required': 'Address is required!'})
    city = forms.CharField(required=True, error_messages={'required': 'Town/City is required!'})
    state = forms.CharField(required=True, error_messages={'required': 'Country/State is required!'})

src/apps/shop/forms.py
from django import forms
from django.forms import ModelForm, TextInput, Textarea, Form
from .models import *


class SearchForm(Form):
    keyword = forms.CharField(max_length=100)


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['subject', 'review', 'rating']

src/templates/common/alerts.html
{% if messages %}
{% endif %}
<style>
    #messages {
        width: 40%;
        position: fixed;
        top: 12px;
        right: 0;
    }
</style>
<div id="messages" class="container">
    {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
                {{ message }}
            </div>   
    {% endfor %}
</div>
<script>
    $(document).ready(() => {
        $(".alert").fadeTo(10000, 500).slideUp(500, function(){
            $(".alert").slideUp(500);
        });
    })
</script>

src/templates/common/breadcrumb.html
 <!--  TODO: Make it reusable  -->
<div class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__links">
                    {% for route in breadcrumb_path.path %}
                    <a href="{{ route.url }}">
                        {% if route.icon %}
                        <i class="{{ route.icon }}"></i>
                        {% endif %}
                        {{ route.title }} 
                    </a>
                    {% endfor %}

                    <span>{{ breadcrumb_path.end.title }}</span>
                </div>
            </div>
        </div> 
    </div>
</div>

src/templates/common/dashboard_sidebar.html
<aside class="col-md-3">
  <!--   SIDEBAR   -->
  <ul class="list-group">
    <a class="list-group-item {% if '/accounts/' == request.path %}active{% endif %}" href="{% url 'dashboard' %}"> Dashboard </a>
    <a class="list-group-item {% if '/my-orders/' in request.path %}active{% endif %}" href="{% url 'my-orders' %}"> My Orders </a>
    <a class="list-group-item {% if '/edit-profile/' in request.path %}active{% endif %}" href="{% url 'edit-profile' %}"> Edit Profile </a>
    <a class="list-group-item {% if '/change-password/' in request.path %}active{% endif %}" href="{% url 'change-password' %}"> Change Password </a>
    <a class="list-group-item btn btn-light btn-block" href="{% url 'logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a>
  </ul>
  <br>
  <!--   SIDEBAR .//END   -->
</aside>

src/templates/common/footer.html
{% load static %}

<!-- Footer Section Begin -->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-7">
                <div class="footer__about">
                    <div class="footer__logo">
                        <a href="./index.html"><img src="img/logo.png" alt=""></a>
                    </div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                    cilisis.</p>
                    <div class="footer__payment">
                        <a href="#"><img src="img/payment/payment-1.png" alt=""></a>
                        <a href="#"><img src="img/payment/payment-2.png" alt=""></a>
                        <a href="#"><img src="img/payment/payment-3.png" alt=""></a>
                        <a href="#"><img src="img/payment/payment-4.png" alt=""></a>
                        <a href="#"><img src="img/payment/payment-5.png" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-5">
                <div class="footer__widget">
                    <h6>Quick links</h6>
                    <ul>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Blogs</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="#">FAQ</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-4">
                <div class="footer__widget">
                    <h6>Account</h6>
                    <ul>
                        <li><a href="#">My Account</a></li>
                        <li><a href="#">Orders Tracking</a></li>
                        <li><a href="#">Checkout</a></li>
                        <li><a href="#">Wishlist</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-8 col-sm-8">
                <div class="footer__newslatter">
                    <h6>NEWSLETTER</h6>
                    <form action="#">
                        <input type="text" placeholder="Email">
                        <button type="submit" class="site-btn">Subscribe</button>
                    </form>
                    <div class="footer__social">
                        <a href="{{ SOCIAL_LINKS.FACEBOOK }}"><i class="fa fa-facebook"></i></a>
                        <a href="{{ SOCIAL_LINKS.TWITTER }}"><i class="fa fa-twitter"></i></a>
                        <a href="{{ SOCIAL_LINKS.YOUTUBE }}"><i class="fa fa-youtube-play"></i></a>
                        <a href="{{ SOCIAL_LINKS.INSTAGRAM }}"><i class="fa fa-instagram"></i></a>
                        <a href="{{ SOCIAL_LINKS.PINTEREST }}"><i class="fa fa-pinterest"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                <div class="footer__copyright__text">
                    <p>Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>. Downloaded from <a href="https://themeslab.org/" target="_blank">Themeslab</a>

</p>
                </div>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

<!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <!-- custom javascript -->
    <script src="{% static 'js/custom.js' %}" type="text/javascript"></script>

src/templates/common/modal-fade.html
<div class="modal" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

src/templates/common/modal.html
<div class="modal fade" id="main-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="main-modal__title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="main-modal__body">
                
            </div>
            <div class="modal-footer" id="main-modal__footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

src/templates/common/navbar.html
{% load static %}

<!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__close">+</div>
        <ul class="offcanvas__widget">
            <li><span class="icon_search search-switch"></span></li>
            <li><a href="{% url 'cart:index' %}"><span class="icon_bag_alt"></span>
                <div class="tip">
                    {{ cart_item_count }}
                </div>
            </a></li>
        </ul>
        <div class="offcanvas__logo">
            <a href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
        </div>
        <div id="mobile-menu-wrap"></div>
        {% if user.id is None %}
        <div class="offcanvas__auth">
            <button class="btn btn-primary" data-toggle="modal" data-target="#modal-login">
                Sign In / Register
            </button>
        </div>
        {% else %}
        <div class="offcanvas__auth">
            <a href="{% url 'dashboard' %}">Hi {{ user.first_name }}</a>
            <a id="logout" data-target="{% url 'logout' %}" href="#">Sign Out</a>
        </div>
        {% endif %}
    </div>
    <!-- Offcanvas Menu End -->

<!-- Header Section Begin -->
    <header class="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-3 col-lg-2">
                    <div class="header__logo">
                        <a href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-7">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a href="{% url 'home' %}">Home</a></li>
                            <!-- <li><a href="#">Women’s</a></li>
                            <li><a href="#">Men’s</a></li> -->
                            <li><a href="{% url 'shop' %}">Shop</a></li>
                            <li><a href="#">Pages</a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'category_list' %}">Categories</a></li>
                                    <li><a href="{% url 'cart:index' %}">Shop Cart</a></li>
                                    <li><a href="{% url 'my-orders' %}">Order history</a></li>
                                    <!-- <li><a href="./blog-details.html">Blog Details</a></li> -->
                                </ul>
                            </li>
                            <!-- <li><a href="./blog.html">Blog</a></li> -->
                            <li><a href="{% url 'contact' %}">Contact</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-xl-3 col-lg-3 col-0">
                    <div class="header__right px-0 justify-content-between align-items-center">
                    
                        <ul class="header__right__widget">
                            <li><span class="icon_search search-switch"></span></li>
                            {% if user.id is not None %}
                            <li><a href="{% url 'cart:index' %}"><span class="icon_bag_alt"></span>
                                <div class="tip">
                                    {{ cart_item_count }}
                                </div>
                            </a></li>
                            {% endif %}
                        </ul>

                        {% if user.id is None %}
                            <div class="header__right__auth">
                                <button class="btn btn-primary" data-toggle="modal" data-target="#modal-login">
                                    Sign In / Register
                                </button>
                            </div>
                        {% else %}
                            <div class="header__right__auth">
                                <a href="{% url 'dashboard' %}">Hi {{ user.first_name }}</a>
                                <a id="logout" data-target="{% url 'logout' %}" href="#">Sign Out</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="canvas__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->


    <script>
        $(function() {
            $("#keyword").autocomplete({
            source: "/shop/search_auto/",
            select: function (event, ui) { //item selected
                AutoCompleteSelectHandler(event, ui)
            },
            minLength: 2,
            });
        });
        function AutoCompleteSelectHandler(event, ui)
        {
            var selectedObj = ui.item;
        }
    </script>

    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form action="{% url 'search' %}" class="search-model-form" method="POST">
                {% csrf_token %}
                <input type="text" class="form-control" style="width:60%;" placeholder="Search here..." id="keyword" name="keyword">
                <br>
			    <div class="input-group-append">
			      <button class="btn btn-dark" type="submit">
			        <i class="fa fa-search"></i>
			      </button>
			    </div>
            </form>
        </div>
    </div>
    <!-- Search End -->